# Generated by Django 3.2.7 on 2021-12-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicewebapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_img',
            field=models.ImageField(blank=True, upload_to='user_imgs/'),
        ),
    ]
