# Generated by Django 3.2.7 on 2022-01-05 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devicewebapp', '0002_alter_userprofileinfo_user_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user_img',
        ),
        migrations.DeleteModel(
            name='DeviceProfileInfo',
        ),
    ]
